# Generated by Django 5.0 on 2024-01-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
