# Generated by Django 5.0 on 2024-01-20 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_shoppingcart_count_wishlist_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'Clothing_item')},
        ),
    ]
