# Generated by Django 5.0 on 2024-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0004_shoppingcart_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_list/media/clothing_images/'),
        ),
    ]
