# Generated by Django 5.0 on 2024-01-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0004_shoppingcart_total_price_and_more'),
        ('review', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='clothing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product_list.clothingitem'),
        ),
    ]
